import type { App } from "@/lib/types"

export const apps: App[] = [
  {
    id: "travel-ai",
    name: "Travel AI Assistant",
    description: "Plan your perfect trip with AI-powered recommendations and itineraries",
    longDescription:
      "Travel AI Assistant helps you plan every aspect of your journey. From finding the best flights and accommodations to creating personalized itineraries based on your interests, budget, and time constraints. The app learns your preferences over time to provide increasingly tailored recommendations.",
    category: "travel",
    icon: "/travel-icon.svg",
    screenshot: "/featured-travel.svg",
    screenshot2: "/travel-screenshot.svg",
    developer: "Travel Tech Inc.",
    version: "2.1.0",
    updated: "Feb 28, 2025",
    size: "45 MB",
    rating: 4.7,
    reviews: 1243,
    free: false,
    price: 4.99,
    permissions: [
      {
        name: "Location",
        description: "Access to your location to provide relevant recommendations",
      },
      {
        name: "Calendar",
        description: "Access to your calendar to schedule and organize your trips",
      },
    ],
  },
  {
    id: "health-nurse",
    name: "AI Health Nurse",
    description: "Your personal health assistant for monitoring and wellness advice",
    longDescription:
      "AI Health Nurse provides 24/7 health monitoring and personalized wellness advice. Track your vitals, get medication reminders, and receive diet and exercise recommendations tailored to your health goals. The app can also help identify potential health issues and suggest when to consult a healthcare professional.",
    category: "health",
    icon: "/health-icon.svg",
    screenshot: "/health-screenshot1.svg",
    screenshot2: "/health-screenshot2.svg",
    developer: "HealthTech Solutions",
    version: "3.2.1",
    updated: "Mar 1, 2025",
    size: "62 MB",
    rating: 4.8,
    reviews: 2156,
    free: true,
    permissions: [
      {
        name: "Health Data",
        description: "Access to health and fitness data to provide personalized recommendations",
      },
      {
        name: "Notifications",
        description: "Send reminders for medications and health activities",
      },
    ],
  },
  {
    id: "shopping-assistant",
    name: "Shopping Assistant",
    description: "Find the best deals and get personalized product recommendations",
    longDescription:
      "Shopping Assistant helps you find the best deals across thousands of online retailers. Get personalized product recommendations based on your preferences, style, and budget. The app can also track price history, alert you when items go on sale, and suggest alternative products that might better suit your needs.",
    category: "shopping",
    icon: "/shopping-icon.svg",
    screenshot: "/placeholder.svg?height=600&width=800",
    screenshot2: "/placeholder.svg?height=600&width=800",
    developer: "ShopSmart Technologies",
    version: "1.5.0",
    updated: "Feb 15, 2025",
    size: "38 MB",
    rating: 4.5,
    reviews: 876,
    free: true,
    permissions: [
      {
        name: "Browser History",
        description: "Access to your browsing history to provide relevant recommendations",
      },
      {
        name: "Notifications",
        description: "Send alerts for price drops and deals",
      },
    ],
  },
  {
    id: "productivity-assistant",
    name: "Productivity Assistant",
    description: "Boost your efficiency with AI-powered task management and scheduling",
    longDescription:
      "Productivity Assistant helps you manage your tasks, schedule, and workflow more efficiently. The AI analyzes your work patterns to suggest optimal times for different types of tasks, automates routine activities, and helps you stay focused with smart notifications and distraction management.",
    category: "productivity",
    icon: "/productivity-icon.svg",
    screenshot: "/placeholder.svg?height=600&width=800",
    screenshot2: "/placeholder.svg?height=600&width=800",
    developer: "Efficiency Labs",
    version: "2.3.4",
    updated: "Mar 5, 2025",
    size: "52 MB",
    rating: 4.6,
    reviews: 1532,
    free: false,
    price: 7.99,
    permissions: [
      {
        name: "Calendar",
        description: "Access to your calendar to schedule and organize tasks",
      },
      {
        name: "Contacts",
        description: "Access to your contacts for collaboration features",
      },
    ],
  },
  {
    id: "creative-writer",
    name: "Creative Writer AI",
    description: "Generate stories, poems, and creative content with AI assistance",
    longDescription:
      "Creative Writer AI helps you overcome writer's block and spark your imagination. Generate stories, poems, and other creative content based on your prompts. The app offers various writing styles, can help develop characters and plots, and provides editing suggestions to refine your work.",
    category: "productivity",
    icon: "/writer-icon.svg",
    screenshot: "/placeholder.svg?height=600&width=800",
    screenshot2: "/placeholder.svg?height=600&width=800",
    developer: "Creative Minds Studio",
    version: "1.2.0",
    updated: "Feb 10, 2025",
    size: "48 MB",
    rating: 4.4,
    reviews: 723,
    free: false,
    price: 3.99,
    permissions: [
      {
        name: "Documents",
        description: "Access to your documents for editing and saving content",
      },
    ],
  },
  {
    id: "language-tutor",
    name: "AI Language Tutor",
    description: "Learn any language with personalized AI-powered lessons and practice",
    longDescription:
      "AI Language Tutor provides personalized language learning experiences tailored to your goals, learning style, and pace. Practice conversations with the AI, receive pronunciation feedback, and track your progress with detailed analytics. The app adapts its teaching methods based on your strengths and weaknesses.",
    category: "education",
    icon: "/language-icon.svg",
    screenshot: "/placeholder.svg?height=600&width=800",
    screenshot2: "/placeholder.svg?height=600&width=800",
    developer: "Polyglot Education",
    version: "4.1.2",
    updated: "Mar 3, 2025",
    size: "75 MB",
    rating: 4.9,
    reviews: 3245,
    free: false,
    price: 9.99,
    permissions: [
      {
        name: "Microphone",
        description: "Access to your microphone for speech recognition and pronunciation practice",
      },
      {
        name: "Notifications",
        description: "Send reminders for practice sessions",
      },
    ],
  },
  {
    id: "music-creator",
    name: "AI Music Creator",
    description: "Create original music with AI-powered composition and production tools",
    longDescription:
      "AI Music Creator helps you compose and produce original music in various genres and styles. Generate melodies, harmonies, and rhythms based on your input, or let the AI create completely new compositions. The app includes virtual instruments, mixing tools, and export options for sharing your creations.",
    category: "entertainment",
    icon: "/music-icon.svg",
    screenshot: "/placeholder.svg?height=600&width=800",
    screenshot2: "/placeholder.svg?height=600&width=800",
    developer: "Harmony Technologies",
    version: "2.0.1",
    updated: "Feb 20, 2025",
    size: "120 MB",
    rating: 4.7,
    reviews: 1876,
    free: false,
    price: 12.99,
    permissions: [
      {
        name: "Microphone",
        description: "Access to your microphone for recording audio input",
      },
      {
        name: "Storage",
        description: "Access to your storage for saving music projects",
      },
    ],
  },
  {
    id: "fitness-coach",
    name: "AI Fitness Coach",
    description: "Get personalized workout plans and real-time exercise feedback",
    longDescription:
      "AI Fitness Coach creates personalized workout plans based on your goals, fitness level, and available equipment. Receive real-time feedback on your form during exercises, track your progress with detailed analytics, and get nutrition recommendations to complement your fitness routine.",
    category: "health",
    icon: "/fitness-icon.svg",
    screenshot: "/placeholder.svg?height=600&width=800",
    screenshot2: "/placeholder.svg?height=600&width=800",
    developer: "FitTech Innovations",
    version: "3.4.0",
    updated: "Mar 2, 2025",
    size: "85 MB",
    rating: 4.6,
    reviews: 2134,
    free: true,
    permissions: [
      {
        name: "Camera",
        description: "Access to your camera for exercise form analysis",
      },
      {
        name: "Health Data",
        description: "Access to health and fitness data to track progress",
      },
    ],
  },
  {
    id: "meditation-guide",
    name: "Meditation Guide AI",
    description: "Personalized meditation sessions with adaptive guidance and ambient sounds",
    longDescription:
      "Meditation Guide AI offers personalized meditation sessions tailored to your mood, goals, and experience level. The app adapts its guidance based on your breathing patterns and focus levels, provides ambient soundscapes to enhance relaxation, and tracks your meditation progress over time.",
    category: "health",
    icon: "/meditation-icon.svg",
    screenshot: "/placeholder.svg?height=600&width=800",
    screenshot2: "/placeholder.svg?height=600&width=800",
    developer: "Mindful Technologies",
    version: "2.2.3",
    updated: "Feb 25, 2025",
    size: "56 MB",
    rating: 4.8,
    reviews: 1543,
    free: false,
    price: 5.99,
    permissions: [
      {
        name: "Microphone",
        description: "Access to your microphone to detect breathing patterns",
      },
    ],
  },
  {
    id: "recipe-chef",
    name: "AI Recipe Chef",
    description: "Discover and create personalized recipes based on your preferences and ingredients",
    longDescription:
      "AI Recipe Chef helps you discover and create recipes based on your dietary preferences, available ingredients, and cooking skills. Get step-by-step cooking instructions, nutritional information, and smart shopping lists. The app learns your taste preferences over time to suggest increasingly personalized recipes.",
    category: "lifestyle",
    icon: "/recipe-icon.svg",
    screenshot: "/placeholder.svg?height=600&width=800",
    screenshot2: "/placeholder.svg?height=600&width=800",
    developer: "Culinary AI Labs",
    version: "1.8.5",
    updated: "Feb 18, 2025",
    size: "68 MB",
    rating: 4.7,
    reviews: 1987,
    free: true,
    permissions: [
      {
        name: "Camera",
        description: "Access to your camera to identify ingredients",
      },
      {
        name: "Storage",
        description: "Access to your storage for saving recipes and meal plans",
      },
    ],
  },
]

